# Use postgres/example user/password credentials
services:
  db:
    image: postgres
    restart: always
    env_file: "/home/admin/docker-env/database.env"
    # set shared memory limit when using docker compose
    shm_size: 128mb
    volumes:
      - "/home/admin/projects/workspace/database/data:/var/lib/postgresql/data"
      - "/home/admin/projects/workspace/database/initscripts:/docker-entrypoint-initdb.d"
    # /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
    #user: 1000:1000
    ports:
      - "127.0.0.1:5432:5432"
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #dev_data:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    #environment:
    #POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080