# .github/workflows/bump-version.yml
name: Auto Bump Version

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node dependencies
        working-directory: MyMusicClientSveltePwa
        run: npm ci

      - name: Bump version (no commit)
        working-directory: MyMusicClientSveltePwa
        run: npm version patch --no-git-tag-version

      # Optional: Commit version bump to the PR branch (not to main)
      - name: Commit version bump to PR branch
        working-directory: MyMusicClientSveltePwa
        run: |
          git pull
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "chore: bump version"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
