#!/bin/bash

# delete dev music and images
sudo rm -r music_dev

# stop dev docker postgres
cd ..
cd dev_database
sudo docker compose down

# delete dev db files
sudo rm -r data/

# restart dev docker
# sudo docker compose up -d