#!/bin/bash

set -e  # Exit on error
RELEASE_FOLDER="$HOME/mymusicbox_production"
DATABASE_FOLDER="$RELEASE_FOLDER/database"

echo "=== Updating executable ==="
go build -buildvcs=false -o "$RELEASE_FOLDER"

echo "=== Navigating to database folder ==="
cd "$DATABASE_FOLDER"

# Uncomment the following line if you want to restart Docker containers
# echo "=== Starting Docker containers ==="
# sudo docker compose up -d

echo "=== Restarting mymusic service ==="
sudo systemctl stop mymusic || echo "Service 'mymusic' was not running."
sudo systemctl daemon-reload
sudo systemctl start mymusic

echo "=== Streaming logs ==="
sudo journalctl -u mymusic.service -f
