#!/bin/bash

set -e  # Exit on error
RELEASE_FOLDER="$HOME/mymusicbox_production"
DATABASE_FOLDER="$RELEASE_FOLDER/database"
SCRIPTS_FOLDER="$DATABASE_FOLDER/initscripts"
IMAGES_FOLDER="$RELEASE_FOLDER/music/images"
COOKIES_FOLDER="$RELEASE_FOLDER/selenium"
MIGRATION_FOLDER="$RELEASE_FOLDER/migration_scripts"
HOTFIX_FOLDER="$RELEASE_FOLDER/hotfix_logs"

echo "=== Checking release folder ==="

FOLDERS=(
  "$RELEASE_FOLDER"
  "$DATABASE_FOLDER"
  "$SCRIPTS_FOLDER"
  "$IMAGES_FOLDER"
  "$COOKIES_FOLDER"
  "$MIGRATION_FOLDER"
  "$HOTFIX_FOLDER"
)

for folder in "${FOLDERS[@]}"; do
  if [ ! -d "$folder" ]; then
    mkdir -p "$folder"
    echo "Created: $folder"
  else
    echo "Exists:  $folder"
  fi
done

echo "=== Copying files ==="
cp migration_scripts/* "$MIGRATION_FOLDER"
cp default/* "$IMAGES_FOLDER"
cp selenium/* "$COOKIES_FOLDER"

echo "=== Updating executable ==="
go build -trimpath -buildvcs=false -ldflags="-s -w" -o "$RELEASE_FOLDER"

echo "=== Reducing executable size ==="
cd "$RELEASE_FOLDER"
upx --best --lzma musicboxapi

echo "=== Restarting mymusic service ==="
sudo systemctl stop mymusic || echo "Service 'mymusic' was not running."
sudo systemctl daemon-reload
sudo systemctl start mymusic

echo "=== Streaming logs ==="
sudo journalctl -u mymusic.service -f
